### ISSUE TITLE
Icons are not rendered on IOS mobile app

### ISSUE THREAD

**Issue by frvkl** [visini/obsidian-icons-plugin#12]
Now the mobile app is out of testing and available in the app store, I am now using the official IOS Obsidian app. Unfortunately, the icons are not rendered on mobile. Any chance you could look into this?

**Comment by marcromeyn** [comment]
Same issue here. Would be awesome if the icons would render on mobile!

**Comment by rjachuthan** [comment]
Yup. Same case with Android as well. Not able to install the plugin itself. Tried installing it on Samsung Galaxy S20.

**Comment by melmaninga** [comment]
+1 for iPadOS
