### ISSUE TITLE
How can I open icon picker?

### ISSUE THREAD

**Issue by Andrii256** [visini/obsidian-icons-plugin#15]
Sounds as stupid question, but I'm serious. What is hotkey?

**Comment by knettles** [comment]
CTRL-Shift-I   

If you bring up the command palette (icon on left side), there's a list of commands for various plug-ins,

**Comment by Andrii256** [comment]
@knettles , thanks :)
I'm newby in obsidian so..

**Comment by Andrii256** [comment]
BTW (if somebody will read it after me): if you have not activated this plugin you will see developer console. But after enable plugin you will see icons picker
