### ISSUE TITLE
Hotkey conflicts

### ISSUE THREAD

**Issue by aprather51** [visini/obsidian-icons-plugin#26]
A lot of time I use Ctrl + Shift + I to bring up developer mode. But when Icon plugin is enabled, it overides it and there's no way to adjust hotkeys. Any suggestions?

**Comment by mjhelto** [comment]
1. Go to ⚙
2. Select **Hotkeys**
3. Type `icon` in the search field
4. Find `Icons: Insert icons`
5. Click the circle with the plus inside it
6. Press `ctrl` + `alt` + `i`
7. Click the _x_ next to the other hotkey to remove it
8. Rejoice, with no more conflicting hotkeys

**Comment by aprather51** [comment]
Thank you!
