### ISSUE TITLE
Update Documentation for customizing the Icons

### ISSUE THREAD

**Issue by acrose99** [visini/obsidian-icons-plugin#7]
This is completely unnecessary but I think it would be useful to people like me just getting into Obsidian, to have a section on customizing the Icons. It took me about 15 minutes reading through all the Obsidian documentation to figure out the most optimal way to apply custom CSS for specific rules and for someone with no experience with Electron/CSS it might be harder.  I wrote an example section you can add to the ReadMe. 

Thanks for all the hard work! 

```
### Customizing Icons

In order to customize the icons in order to change their color, size, etc, you should make a CSS snippet.

To do this, follow the following steps:

1. Go to Settings -> Appearance -> CSS Snippets 
2. Turn on the CSS Snippets option and then click the folder to navigate to it's folder.
3. Make a new file called icons.css
4. Open icons.css in your preferred text editor
5. Add the following:
	```
	.obsidian-icon {
  		... changes go here.
	}
	```
6. Go Back to Settings -> Appearance -> CSS Snippets
7. Click the reload button
8. A button with the title "icons" should appear, turn it on.

Your changes will now be applied and you can edit the file when you want.
```

**Comment by visini** [comment]
Great, many thanks! I'll add it to the project README. Cheers!
